Repository wxWidgets/wxWidgets, pull requests merged in 2022-11, with the labels that each got.

#22939 Document pen styles, joins, and stipple styles
  interface/wx/pen.h
Labels: documentation, backport-3.2

#22942 wxQt: wxEVT_TEXT_ENTER processing fixup
  include/wx/qt/private/winevent.h
  include/wx/qt/textctrl.h
  include/wx/qt/textentry.h
  src/qt/combobox.cpp
  src/qt/textctrl.cpp
  src/qt/textentry.cpp
Labels: Qt

#22952 Fixes to painting wxStaticBox in wxMSW
  include/wx/msw/radiobox.h
  include/wx/msw/statbox.h
  interface/wx/sysopt.h
  samples/widgets/static.cpp
  src/msw/radiobox.cpp
  src/msw/statbox.cpp
Labels: MSW

#22958 Fix measuring menu items text
  include/wx/msw/menuitem.h
  src/msw/menuitem.cpp
Labels: MSW

#22977 wxQt: wxEVT_TEXT_ENTER processing revisited
  include/wx/qt/private/winevent.h
  include/wx/qt/textentry.h
  src/qt/combobox.cpp
  src/qt/menuitem.cpp
  src/qt/radiobox.cpp
  src/qt/spinctrl.cpp
  src/qt/textctrl.cpp
  src/qt/textentry.cpp
  src/qt/toolbar.cpp
  src/qt/window.cpp
Labels: Qt
