Repository wxWidgets/wxWidgets, pull requests merged in 2023-12, with the labels that each got.

#24075 wxStatusBar fixes for wxQt
  include/wx/qt/statusbar.h
  samples/statbar/statbar.cpp
  src/qt/statbmp.cpp
  src/qt/statusbar.cpp
Labels: Qt

#24123 Misc mac fixes
  include/wx/osx/cocoa/private.h
  include/wx/osx/core/private.h
  include/wx/osx/window.h
  include/wx/platform.h
  include/wx/scrolwin.h
  src/common/appbase.cpp
  src/generic/datavgen.cpp
  src/generic/laywin.cpp
  src/generic/scrlwing.cpp
  src/generic/vscroll.cpp
  src/osx/cocoa/renderer.mm
  src/osx/cocoa/window.mm
  src/osx/window_osx.cpp
Labels: macOS

#24131 Make wxSTAY_ON_TOP TLWs transient for parent too in wxGTK
  src/gtk/toplevel.cpp
Labels: GTK

#24135 Some other (important!) wxQt fixes
  include/wx/qt/control.h
  include/wx/qt/dcclient.h
  include/wx/qt/frame.h
  include/wx/qt/listbox.h
  include/wx/qt/private/winevent.h
  include/wx/qt/textctrl.h
  include/wx/qt/window.h
  samples/aui/auidemo.cpp
  src/aui/framemanager.cpp
  src/qt/button.cpp
  src/qt/calctrl.cpp
  src/qt/checkbox.cpp
  src/qt/choice.cpp
  src/qt/combobox.cpp
  src/qt/control.cpp
  src/qt/datectrl.cpp
  src/qt/dcclient.cpp
  src/qt/dialog.cpp
  src/qt/frame.cpp
  src/qt/gauge.cpp
  src/qt/listbox.cpp
  src/qt/listctrl.cpp
  src/qt/menu.cpp
  src/qt/msgdlg.cpp
  src/qt/notebook.cpp
  src/qt/radiobox.cpp
  src/qt/radiobut.cpp
  src/qt/scrolbar.cpp
  src/qt/slider.cpp
  src/qt/spinbutt.cpp
  src/qt/spinctrl.cpp
  src/qt/statbmp.cpp
  src/qt/statbox.cpp
  src/qt/statline.cpp
  src/qt/stattext.cpp
  src/qt/statusbar.cpp
  src/qt/textctrl.cpp
  src/qt/tglbtn.cpp
  src/qt/timectrl.cpp
  src/qt/toolbar.cpp
  src/qt/toplevel.cpp
  src/qt/treectrl.cpp
  src/qt/window.cpp
Labels: Qt
