Repository wxWidgets/wxWidgets, pull requests merged in 2024-02, with the labels that each got.

#24200 wxQt wxGLCanvas improvements and crash fixes.
  include/wx/qt/glcanvas.h
  include/wx/qt/statusbar.h
  include/wx/qt/window.h
  src/qt/combobox.cpp
  src/qt/dcclient.cpp
  src/qt/glcanvas.cpp
  src/qt/statusbar.cpp
  src/qt/window.cpp
Labels: Qt

#24297 Restore correct translation language lookup
  build/cmake/tests/base/CMakeLists.txt
  docs/doxygen/overviews/envvars.h
  include/wx/translation.h
  interface/wx/translation.h
  src/common/translation.cpp
  src/common/uilocale.cpp
  tests/Makefile.in
  tests/intl/en_GB/internat.mo
  tests/intl/en_GB/internat.po
  tests/intl/intltest.cpp
  tests/makefile.gcc
  tests/makefile.vc
  tests/test.bkl
Labels: backport-3.2

#24299 Improve wxMessageDialog in wxQt
  include/wx/qt/msgdlg.h
  src/qt/msgdlg.cpp
Labels: Qt

#24339 Fixes for wxGTK enter/leave window events
  include/wx/gtk/private/event.h
  include/wx/gtk/window.h
  samples/widgets/activityindicator.cpp
  samples/widgets/bmpcombobox.cpp
  samples/widgets/button.cpp
  samples/widgets/checkbox.cpp
  samples/widgets/choice.cpp
  samples/widgets/clrpicker.cpp
  samples/widgets/combobox.cpp
  samples/widgets/datepick.cpp
  samples/widgets/dirctrl.cpp
  samples/widgets/dirpicker.cpp
  samples/widgets/editlbox.cpp
  samples/widgets/filectrl.cpp
  samples/widgets/filepicker.cpp
  samples/widgets/fontpicker.cpp
  samples/widgets/gauge.cpp
  samples/widgets/headerctrl.cpp
  samples/widgets/hyperlnk.cpp
  samples/widgets/listbox.cpp
  samples/widgets/native.cpp
  samples/widgets/notebook.cpp
  samples/widgets/odcombobox.cpp
  samples/widgets/radiobox.cpp
  samples/widgets/searchctrl.cpp
  samples/widgets/slider.cpp
  samples/widgets/spinbtn.cpp
  samples/widgets/statbmp.cpp
  samples/widgets/static.cpp
  samples/widgets/textctrl.cpp
  samples/widgets/timepick.cpp
  samples/widgets/toggle.cpp
  samples/widgets/widgets.cpp
  samples/widgets/widgets.h
  src/gtk/choice.cpp
  src/gtk/srchctrl.cpp
  src/gtk/window.cpp
Labels: GTK
